// Import the necessary dependencies
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import Pied from '@/components/Pied';
import StoreProvider from '@/components/StoreProvider';

// Create an instance of the font
const inter = Inter({ subsets: ['latin'] });

// Export the metadata (if needed)
export const metadata = {
  title: "Taha's Portfolio",
  description: 'Generated by create next app',
};

// Define the RootLayout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Header />
          <main>
            {children}
          </main>
          <Pied />
        </StoreProvider>
      </body>
    </html>
  );
}
